### ISSUE TITLE
error:torch.utils.serialization.read_lua_file.T7ReaderException: unknown type id 1044714758. The file may be corrupted.

### ISSUE THREAD

**Issue by wen-fei** [samyak-268/deep-face-tutorial#1]
The PyTorch version of the VGG-Face pre-trained model may be is corrupted. When I load the model, the problem "torch.utils.serialization.read_lua_file.T7ReaderException: unknown type id 1044714758. The file may be corrupted." happens. Could you upload the .t7 file again?

**Comment by sugiantonehemia** [comment]
I had the same error as well. Could you please upload the file? Thank you in advance.

**Comment by wen-fei** [comment]
I solved this problem because I downloaded the file trained by Pytorch instead of Torch.
i hole that would be useful for you.

**Comment by haha1958** [comment]
> I solved this problem because I downloaded the file trained by Pytorch instead of Torch.
> i hole that would be useful for you.
sorry for bother you ,did you mean you downloaded the file trained by torch then solved this problem? If is ,could you please tell me where did you download it from?

**Comment by wen-fei** [comment]
链接：https://pan.baidu.com/s/1OUBY97CtEL7gXqrIVfkC7A 
提取码：k3yd

**Comment by nirzaa** [comment]
How did you solve this issue?
